---CREACION DE LA BASE DE DATOS Y DE LOS USUARIOS

CREATE database gabo_gym;

CREATE USER gabo_adm WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS 
ENCRYPTED PASSWORD 'g@bo_gym';

CREATE USER gabo_emp WITH NOSUPERUSER LOGIN NOCREATEDB NOCREATEROLE INHERIT REPLICATION ENCRYPTED 
PASSWORD 'g@bo_emp';
CREATE SCHEMA gym;


